name             'strongswanaws'
maintainer       'Christopher Nielsen'
maintainer_email 'christopher.nielsen@gmail.com'
license          'BSD-3-Clause'
description      'Installs/Configures StrongSwan'
long_description 'Installs and configures StrongSwan to connect with an AWS VPN'
version          '0.1.10'
